### PR TITLE
Update serialport to 4.2.0, remove obsolete language constructs, typos

### PR DESCRIPTION
**Pull request by maugier**
Hi,

  Are you looking for a maintainer for this?

  I'm currently doing my own EnOcean project, and using this lib is faster than starting from scratch, but it could use some architectural improvements.

### CODE REVIEW

**Comment by pmirabel** [comment]
> Hi,
> 
> Are you looking for a maintainer for this?
> 
> I'm currently doing my own EnOcean project, and using this lib is faster than starting from scratch, but it could use some architectural improvements.

Hello!

I indeed started this project as a rust training, few years ago.

I never took the time to work back on it but I would be glad to change that.

Would you like to draw some milestones together ?

NB: I am browsing github on my phone right now, and will get back on a décent device later ;)

**Comment by maugier** [comment]
Yes, sure!

  I'm currently trying to pull data from temperature sensors and feed them to Prometheus, using the USB300 stick. I don't really need a full EnOcean lib for that, but I thought it would be nicer.

  Everything in this branch should pass the tests (except for the failing test that was already on your branch); It's small fixes; the big changes are in a new API.

  The things I'm looking at right now are:

- [x] An incremental CRC8 interface
- [ ] Separate framing and packet parsing/building
    - [x] A framing abstraction that only handles ESP3 header, CRC & buffer allocation
    - [ ] Packet parsing/building on top of that 
- [x] Using the stdlib's BufRead/Write interface for reading and writing frames
- [x] Use `num_enum` to simplify byte tags handling
- [ ] Refactor error handling with `thiserror`
- [ ] Make the Packet datatype consistent (i.e. instead of a PacketType field and an enum for the payload, make it directly an enum of payloads )
- [ ] Make the EEP interface extensible
    - [ ] Each EEP should be a distinct type implementing a trait
    - [ ] Should be possible to create a map of EEPs at runtime and use that for parsing

What do you think?

**Comment by pmirabel** [comment]
Hi,
Nice job, back at the time writing this code, you checklist was exactly the "dreamed implementation". 
I would just add basics CI/CD stuff to your list. 

I have to admit that it is my first "real life" experience building a code with people that do not sit on the desk just next to me ;). Maybe you can give me some hints on how to proceed? 

Thx

**Comment by maugier** [comment]
Bah, I'm not that experienced with online collaboration either - but let's see how it goes!

I know almost nothing about CI/CD, so you'll probably have to do it yourself.

I think the best strategy would be to keep the existing API in the existing enocean/eep modules, but introduce new bricks in separate modules (like I did for crc8.rs and frame.rs). Then the old code can be transitioned to use the new code internally, while making sure the tests continue to pass.

First, please let me know what you think of the `frame.rs` interface. It's a bit awkward to have two types for the owned and borrowed versions of a frame, but that's more or less how stdlib does it, I think.

Next, I'll try to come up with a good packet datastructure, and put that in `packet.rs`, and then think about if the communicator can be improved too. Maybe the communicator should depend on a feature flag, so that the dependency to `serialport` can be dropped by people who don't need it?

(btw, the dependency tree for num_enums is quite impressive, but it is compile-time only afaik)

I'll implement as much as I can, and then you can decide if you want to merge the changes or not. I will try not to break any existing code that depends on the current API; currently the only breaking change I did was to change `&Vec<u8>` for `&[u8]`, which is almost always desirable.

**Comment by maugier** [comment]
Other possible longer-term goals:
- [ ] write some macros to automatically implement some EEPs from the official `eep.xml`; 
- [ ] automatically derive packet parsing/building code from a datastructure, using either
   - [ ] a Serde data format, or
   - [ ] a custom Derive macro

**Comment by pmirabel** [comment]
> I know almost nothing about CI/CD, so you'll probably have to do it yourself.  

perfect for me, if you can benefit from this I would be glad 

> I'll implement as much as I can, and then you can decide if you want to merge the changes or not. I will try not to break any existing code that depends on the current API; currently the only breaking change I did was to change &Vec<u8> for &[u8], which is almost always desirable.  

> I think the best strategy would be to keep the existing API in the existing enocean/eep modules, but introduce new bricks in separate modules (like I did for crc8.rs and frame.rs). Then the old code can be transitioned to use the new code internally, while making sure the tests continue to pass.    

Given all the warnings in the readme, plus cargo dependencies management, I think it would be OK to break API (we'll just have to stick with semver, which I will take care in CI/CD stuff). 
Nice idea to smoothen transition though.

> First, please let me know what you think of the frame.rs interface. It's a bit awkward to have two types for the owned and borrowed versions of a frame, but that's more or less how stdlib does it, I think.    

Well, that was my first thought also, but I cannot find any "more idimoatic" way to achieve same functionnality.   

> Maybe the communicator should depend on a feature flag, so that the dependency to serialport can be dropped by people who don't need it?    

Nice idea, I can work on this if you want (though I have no idea how to do it yet)


> (btw, the dependency tree for num_enums is quite impressive, but it is compile-time only afaik)  

Thx for that, I sure will use this in another projects !

**Comment by maugier** [comment]
I discovered that using BufReader does not work on Windows. The idea was to make opportunistic big reads, but apparently on Windows it won't return partial reads unless EOF is reached (so, for a serial port, never).

The frame interface now uses Read instead of BufRead, meaning it could fail to synchronize if it repeatedly receives frames with 0x55 in the last 6 bytes of the frame. That should be fixed.

Here is a proposal for a basic communication port API.

The response packets (type 0x02) are synchronous in nature, but you cannot parse them properly without knowledge of the last request.

I want to make the port synchronous: after sending a request (type 0x05, or others that expect an answer), the port immediately starts to look for a response. Non-response packets will be queued, and delivered on subsequent read calls. Only when the queue is empty do we actually read the port.

For the packet interface, for now, all of them favor borrowing over owning. This is because borrowing is best for assembling packets without copy, and for parsing packets owned by the caller.

One possibility would be to use two different datatypes, one for received packets (owned) and one for packets about to be sent(borrowed). That also helps the user (no need to match for packet types that are only host->device after a parse, for instance), but it makes the lib unusable for anyone who'd like to do a device-side implementation. But maybe we should not care about device-side implementation?

**Pull request merged**
